Sruth/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ai.urls')),
]

ai/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.make_question, name='home'),  # Home page with form
    # path('ask/', views.make_question, name='ask_question'),  # Form submission URL
]

ai/models.py
from django.db import models

class Ai(models.Model):
    question = models.TextField(blank=True,null=True)
    answer = models.TextField(blank=True,null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateField(auto_now=True)

    def __str__(self):
        return self.question[:50]

ai/forms.py
from django import forms
from .models import Ai

class AiForm(forms.ModelForm):
    class Meta:
        model = Ai
        fields = ['question']

ai/views.py
from django.shortcuts import render
import os
from dotenv import load_dotenv
from groq import Groq
from .models import Ai
from .forms import AiForm

# the AI key and setup
MY_KEY = os.getenv('SRUTH_KEY')
client = Groq(
    api_key=MY_KEY
)


def ai_response(question):
    response = client.chat.completions.create(
    model="llama-3.3-70b-versatile",
    messages=[
        {
            "role": "system",
            "content": 'You are very empathic. You will give honest and genuine advice. But if anyone asks anything about you, You will say you are a cat named Sruth.'
        },
        {
            "role": "user",
            "content": question
        }
        
    ],
    temperature=1,
    )
    return response.choices[0].message.content



def make_question(request):
    if request.method == "POST":
        ai_form = AiForm(request.POST)
        if ai_form.is_valid():
            chat = ai_form.save(False)
            response = ai_response(ai_form.cleaned_data['question'])
            chat.question = ai_form.cleaned_data['question']
            chat.answer = response
            chat.save()
            ai_form = AiForm()
    else:
        ai_form = AiForm()
    all_chat_list = Ai.objects.all()
    
    return render(request,'index.html',{'form':ai_form,'all_chat_list':all_chat_list})

ai/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,100;0,300;0,400;0,700;0,900;1,100;1,300;1,400;1,700;1,900&display=swap" rel="stylesheet">

    <title>Ai Design</title>

    <style>
        *{
            font-family: "Lato", serif;
            color: white;
            background-color: black;

        }
        .header{
            position: relative;
            
        }
        .content{
            max-width: 80%;
            margin: 0px auto;
        }
        .form-container{
            max-width: 1044px;
            margin: 0 auto;
            display: flex;
            justify-content: center;
            align-items: center;
        }
        form{
            display: flex;
            justify-content: space-evenly;
            gap: 20px;
        }

        form input[type=submit]{
            width: 100px;
            height: 40px;
            border-radius: 4px;
            border: 1px solid gray;
        }
        form textarea{
            width: 800px;
            border-radius: 8px;
            padding: 10px;
            border: 1px solid gray;
        }

        label[for='question']{
            display: none;
        }
        .chat-container{
            height: 60vh;
            overflow-y: scroll;
            display: flex;
            flex-direction: column;
            flex: 1;
        }
        .chat{
            max-width: 50%;
            padding: 10px 20px;
            border-radius: 10px;
            margin: 10px 15px;
            border: 1px solid gray;
        }
        .answer-container{
            display: flex;
            align-self: flex-start;
        }
        .question-container{
            display: flex;
            align-self: flex-end;
        }
        label[for='id_question'] {
            display: none;
        }
    </style>
</head>

<body>
    <div class="content">
        <div class="header">
            <h1>Sruth Ai</h1>
        </div>
        <div class="chat-container">
            {% for chat in all_chat_list %}
                <div class="chat question-container">
                    <p>{{chat.question}}</p>
                </div>
                <div class="chat answer-container">
                    <pre style="white-space: pre-wrap;">{{ chat.answer }}</pre>
                </div>
            {% endfor %}
        </div>
    </div>
    {% load crispy_forms_tags %}
    {% comment %} Question Form {% endcomment %}
    <div class="form-container">
        <form method='post'>
            {% csrf_token %}
            {{ form }}
            <input type='submit' value="Submit">
        </form>
    </div>

    <script>
        document.addEventListener("DOMContentLoaded", function () {
            const chatContainer = document.querySelector(".chat-container");
            function scrollToBottom() {
                chatContainer.scrollTop = chatContainer.scrollHeight;
            }
        
            const observer = new MutationObserver(scrollToBottom);
            observer.observe(chatContainer, { childList: true });
        
            scrollToBottom();
        });                
    </script>
    
</body>
</html>